# Generated by Django 4.2.7 on 2023-11-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
