# Generated by Django 4.2.7 on 2024-01-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_author_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-time_create'], 'permissions': [('set_is_published', 'Может менять статус публикации'), ('set_description', 'Может изменять описание'), ('set_category', 'Может изменять категорию')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
