# Generated by Django 4.2.7 on 2023-12-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-version_number'], 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='version',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.PositiveIntegerField(verbose_name='Номер версии'),
        ),
    ]
