# Generated by Django 4.2.7 on 2023-12-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_version_options_alter_version_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-is_active', '-version_number'], 'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(choices=[(1, 'Опубликовано'), (0, 'Черновик')], default=1, verbose_name='Опубликовано'),
        ),
    ]
